# -*- coding: utf-8 -*-
"""cats&dogs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QAcm8lA_KyT2HS0NAnof-_Pn5Y6oFlA
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
import numpy as np

# Load dataset
(ds_train, ds_val), ds_info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:]'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

# Preprocessing
def preprocess(image, label):
    image = tf.image.resize(image, (128, 128))
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

# Prepare datasets
ds_train = ds_train.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE).batch(8).prefetch(tf.data.AUTOTUNE)
ds_val = ds_val.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE).batch(8).prefetch(tf.data.AUTOTUNE)

# CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(128, 128, 3)),==
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(64, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(128, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Binary output
])

# Compile and train
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(ds_train, epochs=5, validation_data=ds_val)

# Evaluate
loss, acc = model.evaluate(ds_val)
print(f"\n✅ Validation accuracy: {acc:.4f}")

# --- PREDICTION SECTION ---
# Take some images from validation set
for images, labels in ds_val.take(1):  # Take one batch (8 images)
    preds = model.predict(images)
    preds = (preds > 0.5).astype(int)  # Convert probabilities to 0 or 1

    plt.figure(figsize=(12, 6))
    for i in range(len(images)):
        plt.subplot(2, 4, i + 1)
        plt.imshow(images[i])
        true_label = "Dog" if labels[i].numpy() == 1 else "Cat"
        pred_label = "Dog " if preds[i][0] == 1 else "Cat "
        color = "green" if true_label.split()[0] == pred_label.split()[0] else "red"
        plt.title(f"True: {true_label}\nPred: {pred_label}", color=color)
        plt.axis("off")
    plt.show()